apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edt-data
  namespace: enterprise-digital-twin
  labels:
    app.kubernetes.io/name: enterprise-digital-twin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi